-- Role: pstefan
-- DROP ROLE IF EXISTS pstefan;

CREATE ROLE pstefan WITH
  LOGIN
  NOSUPERUSER
  INHERIT
  NOCREATEDB
  NOCREATEROLE
  NOREPLICATION
  ENCRYPTED PASSWORD 'SCRAM-SHA-256$4096:mOYQ5+E9ofGrccDRrMy02w==$28ixJ41TKQ3ZhdEZefrIhPcjpLrB6wICRhASFg1ULyQ=:YiUmygRMDCLYeJitROIsKithHtsBGFZM+phbcyOzgvM=';=';